quora/pyanalyze

pyanalyze/value.py

Experiments showed that merging with NewTypeValue isn't realistic. We
infer too many things as being a VariableNameValue that are actually
something else.

VariableNameValue: remove TODO

---

pyanalyze/annotations.py
pyanalyze/arg_spec.py
pyanalyze/name_check_visitor.py
pyanalyze/test_arg_spec.py
pyanalyze/test_name_check_visitor.py

By reusing `type_from_ast()` from `pyanalyze.annotations`, instead of rolling our own.
Also make a few fixes to deal with the fallout from this change:
- Make the missing await detector also detect `asyncio.Future`
- Support in-place methods properly
- Hardcode a more forgiving type for `typing.NewType`

Improve typeshed type processing

---

pyanalyze/annotations.py
pyanalyze/asynq_checker.py
pyanalyze/attributes.py
pyanalyze/name_check_visitor.py
pyanalyze/test_arg_spec.py
pyanalyze/test_asynq_checker.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_value.py
pyanalyze/value.py

This lets us correctly handle generic methods with explicit self types, like in the new test case in test_arg_spec. It does not yet handle similar methods without an explicit type; I need to find a way to set a correct type for `self` on those.

Make UnboundMethodValue store the value of its self object

---

pyanalyze/arg_spec.py
pyanalyze/name_check_visitor.py
setup.py

Was only used for inspect2.iscoroutinefunction, but that's been
in the stdlib since 3.5, so we don't need the backport.
https://docs.python.org/3/library/inspect.html#inspect.iscoroutinefunction

remove inspect2 dep

---

pyanalyze/node_visitor.py

So it doesn't produce invalid paths. `commonpath()` was new in 3.5, so we couldn't do this when we still needed to support Python 2.

markdown report: use commonpath

---

pyanalyze/arg_spec.py
pyanalyze/test_arg_spec.py
pyanalyze/test_value.py
pyanalyze/value.py

pyanalyze didn't allow you to pass a `BytesIO` object to an argument typed as `typing.IO` because of the vagaries of typeshed file structure and because of an overly strict check in `GenericValue.can_assign`.

Fix for assigning a BytesIO to an IO object

---

pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/signature.py
pyanalyze/stacked_scopes.py
pyanalyze/test_implementation.py

This covers:
- `list.append`
- `list.extend`
- `list.__add__`
- `set.add`
- `dict.__setitem__`
For all of these, we now either check that the types of the new items match expectations, or we broaden the type of the object. Example behavior:
```
lst = []
lst.append(3)
dump_value(lst)  # <list containing [Literal[3]]>
```

add implementation for container mutator methods

---

pyanalyze/annotations.py
pyanalyze/name_check_visitor.py
pyanalyze/test_name_check_visitor.py

Now it no longer just assumes the first type argument is the value we iterate over. This comes up in practice with `ItemsView`.

Fix iterable check

---

pyanalyze/arg_spec.py
pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/node_visitor.py
pyanalyze/signature.py
pyanalyze/test_arg_spec.py
pyanalyze/test_implementation.py
pyanalyze/value.py

For now, just use it for hardcoded signatures in implementation.py. The only concrete difference so far should be that positional-only arguments are handled correctly.
First step for #51

Add new Signature object wrapping inspect.Signature

---

pyanalyze/signature.py

This way, implementation functions don't have to worry about basic type checking.

Don't call implementation functions if there is an error

---

pyanalyze/annotations.py
pyanalyze/arg_spec.py
pyanalyze/name_check_visitor.py
pyanalyze/signature.py
pyanalyze/test_arg_spec.py
pyanalyze/test_config.py

Closes #51 
A user-visible effect is that this makes pyanalyze better at recognizing *args/**kwargs annotations in function definitions. It doesn't help (yet) with *args/**kwargs in calls (#63).

clean up ExtendedArgSpec

---

pyanalyze/arg_spec.py
pyanalyze/test_arg_spec.py

They might come from the original function and be incorrect.

Ignore all annotations on @wrapped functions

---

pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_value.py
pyanalyze/value.py

This infers more precise types for unpacking assignments (`a, b = c`) and unpacking in collection displays (`[*a, *b]`).
Fixes #72. Fixes part of #66 (not for dictionaries). Works towards fixing #63
(now *args are ignored at a lower level in the stack).

add concrete_values_from_iterable

---

pyanalyze/name_check_visitor.py
pyanalyze/test_name_check_visitor.py

This causes issues when we use attributes on the nested class that `type` doesn't have. Fixes some false positives from #103.

don't infer TypedValue(type) for nested classes

---

pyanalyze/annotations.py
pyanalyze/arg_spec.py
pyanalyze/name_check_visitor.py
pyanalyze/test_arg_spec.py
setup.py

Notably, this includes support for recognizing NewTypes in stubs, which is necessary because typeshed-client now picks up the stubs for qcore, which include some NewTypes.

Support for the new version of `typeshed-client`

---

pyanalyze/analysis_lib.py
pyanalyze/annotations.py
pyanalyze/attributes.py
pyanalyze/extensions.py
pyanalyze/find_unused.py
pyanalyze/format_strings.py
pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/signature.py
pyanalyze/stacked_scopes.py
pyanalyze/test_annotations.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_value.py
pyanalyze/value.py

We keep Annotated around at runtime, which risks incomplete support but enables us to use Annotated types in the future.

add support for Annotated

---

README.md
pyanalyze/annotations.py
pyanalyze/extensions.py
pyanalyze/test_annotations.py
pyanalyze/test_extensions.py

Fixes #142. Unfortunately, some more advanced use cases still do not work.

improve runtime representation of AsynqCallable

---

pyanalyze/test_value.py
pyanalyze/value.py

Fixes #157
This is a simpler solution than proposed in the issue, but empirically it already fixes the bottleneck.
This also fixes a bug where we'd allow KnownValues of different types that compare equal to intermix.

Optimize MultiValuedValue.can_assign

---

pyanalyze/name_check_visitor.py
pyanalyze/test_stacked_scopes.py

Fixes a regression from #167 to #168. We sometimes infer the type of local variables as NO_RETURN_VALUE, but that can lead to spurious entries being added to the `%LEAVES_SCOPE` magical variable.

Be less eager with setting NO_RETURN_VALUE

---

pyanalyze/__init__.py
pyanalyze/analysis_lib.py
pyanalyze/ast_annotator.py
pyanalyze/importer.py
pyanalyze/name_check_visitor.py
pyanalyze/test_ast_annotator.py
pyanalyze/test_name_check_visitor.py
pyanalyze/typeshed.py

Fixes #166 
Plus some related changes:
- Make the importer fall back to importing outside sys.path (which seems generally useful)
- Make name_check_visitor.py work a bit better if self.module is None
- Ensure all expressions have an annotation set

add documented code for AST annotation

---

pyanalyze/name_check_visitor.py
pyanalyze/test_name_check_visitor.py
pyanalyze/value.py

Now `a, *b, c` is typed correctly, and unpacking involving Unions is more likely to give precise types.

Improve iterable unpacking

---

pyanalyze/attributes.py
pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/safe.py
pyanalyze/stacked_scopes.py
pyanalyze/test_attributes.py
pyanalyze/test_stacked_scopes.py

If a module has `__annotations__`, use those instead of the actual runtime type.

use module-level __annotations__ for types

---

pyanalyze/arg_spec.py
pyanalyze/test_signature.py
pyanalyze/tests.py

Saw this in testing on a class that manually sets `__name__`. I wasn't able to reproduce
it in a pyanalyze unit test but added tests for some similar scenarios.

fix __bases__ bug

---

pyanalyze/annotations.py
pyanalyze/name_check_visitor.py

In Python 3 all function arguments are created through `arg` nodes. This check was only necessary in Python 2.

Remove redundant code from unused argument checker

---

pyanalyze/node_visitor.py

Fixes #211 
Allows checks to be disabled with `-d` when `--enable-all` is passed, to support a strict default-enabled/deny-list approach to checks. Furthermore, adds a new `--disable-all` flag to the CLI, which disables all checks except those enabled with `-e`, to support a default-disabled/allow-list approach.
There didn't appear to be an obvious one-letter equivalent (`-A` and `-a` were already taken, as was `-d`, and `-D` was potentially confusingly not parallel with `-a`. However, if you want me to add one, I certainly can.
I've manually tested this in a variety of cases locally, but I'm not sure what, if anything, should be done about tests. I couldn't find where CLI args were tested, so I'm not sure what the current approach is. And while I'm reasonably experienced with pytest and …

Add --disable-all CLI flag and allow enabling/disabling specific checks when --*-all passed

---

pyanalyze/node_visitor.py

Sorry I didn't get this in for v0.3.0! If no path is specified on the command line, `pyanalyze` will default to checking the current working directory, like `flake8`, rather than erroring out and dumping a traceback. Tested with and without paths passed and by using the entrypoint and `python -m`.
Fixes #219

Default to the CWD and don't dump a traceback if no path specified

---

pyanalyze/__main__.py

Fixes #224 
Ensures that Pyanalyze exits non-zero (with the exit code returned by `NameCheckVistor.main()`) if called from the CLI and an error occurs. This makes it usable as a pre-commit hook and with CIs, and matches other linters where this behavior is standard.

Return non-zero if called from the CLI and an error occurs

---

pyanalyze/config.py

We no longer use this attribute. Metaclasses should instead use `used()` to mark classes as used.

Remove ALLOWED_METACLASSES

---

pyanalyze/value.py

This made it unnecessarily drop the metadata from the AnnotatedValue.

remove special case from MultiValuedValue.can_assign

---

pyanalyze/attributes.py
pyanalyze/name_check_visitor.py
pyanalyze/signature.py
pyanalyze/test_signature.py
pyanalyze/value.py

Previously, we used a very simple algorithm for resolving TypeVars: the first assignment wins. Now, we instead unify all the values from different parameters, which is a more standard approach. But it turned out we were relying on the previous behavior in order to get correct behavior with methods on generic classes, where we really do want to believe what the first argument is telling us (if we're in a `list[int]` and we type check `lst.append("str")`, we should reject the call, not conclude that the value of the TypeVar is `int | "str"`). To do that, we introduce a new concept where `KnownValue` and `UnboundMethodValue` can remember typevars applied to them, so we can set them correctly when we create a signature from the value.

change how TypeVar instantiation works

---

pyanalyze/name_check_visitor.py
pyanalyze/test_name_check_visitor.py

This should be done in type annotations or impl methods instead.

remove special case for __index__ call

---

pyanalyze/implementation.py
pyanalyze/typeshed.py

* The definition of `inspect.Parameter.empty` changed and caused crashes, because we weren't handling unannotated assignments
* The definition of dict.items changed to return a private class. We currently don't handle that. Fixing that is probably going to be a big refactor, so punting on it for now.

Deal with new typeshed-client release

---

README.md
pyanalyze/annotations.py
pyanalyze/attributes.py
pyanalyze/format_strings.py
pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/stacked_scopes.py
pyanalyze/test_annotations.py
pyanalyze/test_name_check_visitor.py
pyanalyze/typeshed.py
pyanalyze/value.py

I'd been thinking of doing this for longer, but now I have a motivating use case. A CustomCheck that excludes Any may still want to allow one specific unavoidable kind of Any: the type of the element of an empty list. To support that, we replace the singleton `UNRESOLVED_VALUE` with instances of a new class `AnyValue` that provides a `source`.
This PR merely creates the enum and replaces `is UNRESOLVED_VALUE` checks within pyanalyze. After I migrate some internal code, I will replace usages of UNRESOLVED_VALUE within pyanalyze.

add concept of AnySource

---

pyanalyze/node_visitor.py
pyanalyze/signature.py

Another step towards *args/**kwargs type checking. Also found two issues within pyanalyze itself.

Don't throw away the return value for args/kwargs calls

---

README.md
pyanalyze/config.py
pyanalyze/name_check_visitor.py
pyanalyze/test_implementation.py
pyanalyze/test_name_check_visitor.py

For example, we'll now infer `[x for x in (1, 2)]` as `SequenceIncompleteValue(list, [KnownValue(1), KnownValue(2)])`. I expect this to help with some edge cases from #275.

Infer precise types for comprehensions over known iterables

---

pyanalyze/safe.py

Fails if obj is a pandas DataFrame (don't ask me why)

Fix is_typing_name()

---

docs/changelog.md
pyanalyze/test_typeshed.py
pyanalyze/typeshed.py

urllib.parse._ParseResultBase.__qualname__ is ParseResult.

Fix typeshed bases with incorrect __qualname__

---

docs/changelog.md
pyanalyze/annotations.py
pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/signature.py
pyanalyze/stacked_scopes.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_signature.py
pyanalyze/test_stacked_scopes.py
pyanalyze/test_value.py
pyanalyze/value.py

This allows storing constraints in variables. As a result, we need a way to invalidate constraints if the underlying variable has been reassigned since the constraint was created, and to that end each Varname is now associated with an origin, the nodes in which it was defined.

Put constraints in Annotated metadata

---

pyanalyze/name_check_visitor.py

I swapped the previous values when migrating these.

Fix values of union and comprehension limits

---

setup.py

No longer relying on the env var to set the version. We can still use it as a marker to trigger Cython compilation.

Update setup.py internal integration

---

docs/changelog.md
pyanalyze/name_check_visitor.py
pyanalyze/signature.py
pyanalyze/stubs/_pyanalyze_tests-stubs/overloaded.pyi
pyanalyze/test_signature.py
pyanalyze/test_typeshed.py
pyanalyze/typeshed.py

Specifically, in cases where the default was Any and the default was used. This is most likely to happen with stubs, where the default value is always `...`.

Fix bug that led to some overloaded calls incorrectly resolving to `Any`

---

docs/changelog.md
pyanalyze/value.py

I noticed significant time being spent repeatedly constructing the set of known subvalues. On a profiled run on our maiin internal codebase, this makes pyanalyze ~30% faster.

Further MultiValuedValue optimization

---

docs/changelog.md
pyanalyze/error_code.py
pyanalyze/name_check_visitor.py
pyanalyze/value.py
pyanalyze/yield_checker.py

Part of #64.
This is very noisy and finds tons of issues in pyanalyze's own code.

add inferred_any

---

docs/changelog.md
pyanalyze/name_check_visitor.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_operations.py

in and not in always return bool

---

docs/changelog.md
pyanalyze/asynq_checker.py
pyanalyze/name_check_visitor.py
pyanalyze/test_asynq_checker.py

We no longer need this internally.
﻿

Remove support for detecting properties that represent synchronous equivalents of asynq methods

---

docs/changelog.md
pyanalyze/name_check_visitor.py
pyanalyze/stacked_scopes.py
pyanalyze/test_name_check_visitor.py

The existing logic doesn't recognize that you can break out of loops inside of an `if` statement, since it only checks for `LEAVES_LOOP` in the main scope.

While Loops: handle exiting a loop from within a conditional block

---

docs/changelog.md
pyanalyze/implementation.py

This was added because using typeshed exposed some TypeVar bugs
previously. But now pyanalyze's TypeVar resolution algorithm is
better and we shouldn't need this special case any more.

Remove sorted() signature

---

docs/changelog.md
pyanalyze/implementation.py
pyanalyze/test_implementation.py

Now list(Sequence[A] | Sequence[B]) will be list[A] | list[B] instead of list[A | B].

Improve type inference for calls to `set()`, `list()`, and `tuple()` with union arguments

---

docs/changelog.md
pyanalyze/arg_spec.py
pyanalyze/attributes.py
pyanalyze/name_check_visitor.py
pyanalyze/signature.py
pyanalyze/test_signature.py
pyanalyze/value.py

- Correctly check the `self` argument to `@property` getters
- fix local return values
- remove PropertyArgSpec

Correctly check the `self` argument to `@property` getters

---

docs/changelog.md
pyanalyze/annotations.py
pyanalyze/boolability.py
pyanalyze/functions.py
pyanalyze/name_check_visitor.py
pyanalyze/test_async_await.py

Enough to make it importable and to make most tests pass.
At least two bugs remain:
- It crashes on any Enum due to some issue with the base type resolver
- It incorrectly wants some "self" parameters to be annotated

Start support for Python 3.11

---

docs/changelog.md
pyanalyze/error_code.py
pyanalyze/name_check_visitor.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_stacked_scopes.py

Based on feedback that the existing error message was confusing.

add unused_assignment

---

docs/changelog.md
pyanalyze/arg_spec.py
pyanalyze/implementation.py
pyanalyze/name_check_visitor.py
pyanalyze/test_async_await.py
pyanalyze/test_asynq.py
pyanalyze/test_implementation.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_signature.py
pyanalyze/test_stacked_scopes.py
pyanalyze/test_typeshed.py
pyanalyze/value.py

With the new support for variable-length elements in SequenceValue,
we can use a SequenceValue with a single variable-length element
instead of a "weak" list. The behavior should be roughly equivalent.

Remove WeakExtension

---

pyanalyze/signature.py
pyanalyze/value.py

Planning to add a feature that will use this.

Allow CanAssignError to specify an error code

---

docs/changelog.md
pyanalyze/name_check_visitor.py
pyanalyze/test_operations.py

Support "in" on objects with __getitem__

---

setup.py

We use assert_never() which is new in 4.1.0.
Fixes #581.

Update typing-extensions requirement

---

docs/changelog.md
pyanalyze/attributes.py
pyanalyze/test.toml
pyanalyze/test_attributes.py
pyanalyze/test_config.py

This is a more useful version of treat_class_attribute_as_any.
The use case I envision is to replace ORM fields with their values.

Add `class_attribute_transformers` hook

---

pyanalyze/safe.py

isinstance() is even less safe than I thought.
Proof:
```
>>> class X:
...     @property
...     def __class__(self): 1/0
... 
>>> isinstance(X(), int)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 3, in __class__
ZeroDivisionError: division by zero
```

Fix comments on safe_isinstance()

---

docs/changelog.md
pyanalyze/node_visitor.py

On some TensorFlow module, getattr(module, "__flle__", None) can throw a TypeError.

Be more paranoid with attribute access on modules

---

README.md

Hi.
Just a small fix.
It seems documentation was moved in https://github.com/quora/pyanalyze/commit/14341fcadc26b08c8776296cad2c307aa5171e4f but link was not updated.

Fix broken link to "Type System" details in README

---

docs/faq.md

- pyanalyze now supports overloads, both in stubs and at runtime
- CPython's typing.py was changed to allow runtime introspection of overloads

Update discussion of overloads

---

docs/changelog.md
pyanalyze/name_check_visitor.py
pyanalyze/test_attributes.py

This reverts commit b3d2824f7ce9c6ca3ff6cb58f6f7f7c8ecacb2d3.
Seems to have caused a performance regression.

Revert "Fix name mangling (#658)"

---

docs/annotated_types.md
docs/changelog.md
docs/index.rst
pyanalyze/__init__.py
pyanalyze/annotated_types.py
pyanalyze/annotations.py
pyanalyze/name_check_visitor.py
pyanalyze/test_annotated_types.py
pyanalyze/test_stacked_scopes.py
setup.py

This adds support for checking `annotated_types` annotations against literals, as well as a few tricks to make them more usable:
- Allowing stronger annotations where a weaker one is requested; for example, allow `Annotated[int, Gt(6)]` where `Annotated[int, Gt(5)]` is requested.
- Inferring annotations in some cases (`if x > 5:` essentially adds the annotation `Gt(5)`).
Future work:
- We should also infer predicates for `if len(x) > 5:` but we currently don't.

Support for annotated_types

---

docs/changelog.md
pyanalyze/name_check_visitor.py
pyanalyze/node_visitor.py

Add -c option

---

pyanalyze/implementation.py
pyanalyze/runtime.py
pyanalyze/test_runtime.py

I realized this order makes more sense, for consistency with isinstance(). Let's change it
now before a release goes out.

Flip the order of the arguments to is_compatible

---

docs/changelog.md
pyanalyze/implementation.py
pyanalyze/test_implementation.py

Error for call to Any

---

docs/changelog.md
pyanalyze/options.py

This PR implements the "white-list" feature for `pyproject.toml`. Adding `disable-all = true` will automatically disable all rules but the ones indicated in the `pyproject.toml`. While I was doing it, I thought that maybe `disable-all-default-rules` would be more explicit, but I left the `disable_all` to be more consistent with the CLI implementation.
Regarding the tests, tell me if it is needed to write some.
About the implementation itself, maybe there might be better ways of doing. Specially for the function that gets all error codes. Maybe there is a util-based function that already does that.
Linked to #648

feat: pyproject whitelist

---

docs/changelog.md
pyanalyze/name_check_visitor.py
pyanalyze/test_typeis.py
pyanalyze/value.py

- Start can_assign
- Further fix can_assign()
- one more fixed
- changelog

Fix some higher-order behavior of `TypeGuard` and `TypeIs`

---

pyanalyze/name_check_visitor.py

The existing message was too verbose and arguably the compatibility
was in the wrong direction.
For comparison:
- Pyre: Incompatible return type [7]: Expected `str` but got `bool`
- Mypy: Incompatible return value type (got "bool", expected "str")
- Pyright: Expression of type "Literal[False]" cannot be assigned to return type "None"

Improve error message for incompatible return type

---

docs/changelog.md
pyanalyze/arg_spec.py
pyanalyze/implementation.py
pyanalyze/test_annotations.py
pyanalyze/test_implementation.py

Fix creating TypeVar and others in non-executed code

---

docs/changelog.md
pyanalyze/stacked_scopes.py
pyanalyze/test_name_check_visitor.py
pyanalyze/test_stacked_scopes.py

A suspiciously simple fix but I think it's correct.
Fixes #597

Fix possibly_undefined_name on use of the walrus operator

---

pyanalyze/typeshed.py

If no search_path is passed, typeshed-client uses a subprocess to find sys.path (because
it supports getting paths for another Python interpreter). Here we don't need that; just
pass sys.path directly.

Improve performance of constructing typeshed_client

---

pyanalyze/__main__.py

I still use windows cmd, and the color codes used by pyanalyze do not work on there, instead printing a bunch of codes like `←[37m    ←[39;49;00ms`, However, for [whatever reason](https://github.com/python/cpython/issues/74261) you can fix this simply by calling `os.system("")` once.
I am making this a pull request, even though I am not sure where to best put the code that fixes this, in case the placement of the code doesn't matter and the PR saves everyone some trouble.

Enable ANSI color codes for windows cmd

---

pyanalyze/arg_spec.py
pyanalyze/name_check_visitor.py
pyanalyze/test_asynq.py
requirements.txt
setup.py

This essentially mimics the `.asynq` support:
* The argument type handling is the same
* The return type handling is similar, but use `Awaitable` instead of `asynq.Future`

Infer precise type for fn.asyncio
