quora/pyanalyze

pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/name_check_visitor.py, pyanalyze/test_annotations.py
=> python 3.9: handle GenericAlias properly

pyanalyze/name_check_visitor.py, pyanalyze/test_name_check_visitor.py
Noticed this while trying to improve unused name detection.
=> visit class kwargs

pyanalyze/find_unused.py
Users should just use should_ignore_unused().
=> remove various config options around --find-unused

pyanalyze/config.py, pyanalyze/find_unused.py, pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py, pyanalyze/test_self.py
Also fixes a bug where we did not run the ClassAttributeChecker in some
cases, and some bugs this surfaced in pyanalyze's own code.
=> add option to enforce no unused objects

pyanalyze/name_check_visitor.py, pyanalyze/stacked_scopes.py, pyanalyze/test_name_check_visitor.py
Also fix inference for the not operator.
Fixes #24.
=> Fix type inference for boolean ops

pyanalyze/find_unused.py, pyanalyze/name_check_visitor.py
To enable post-processing of unused objects in client code.
=> make it possible to return unused objects in a structured format

pyanalyze/annotations.py, pyanalyze/name_check_visitor.py, pyanalyze/test_annotations.py
- Tests for list[int] and tuple[]
- Fixes for tuple[]
- Support for int | None in stringified annotations
=> Support some newer typing constructs

pyanalyze/asynq_checker.py, pyanalyze/name_check_visitor.py
Cython miscompiles the dataclass
=> move FunctionInfo to a different file

pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/test_arg_spec.py
Another step towards slightly better generic methods
=> support inferring the self type for simple methods

pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/config.py, pyanalyze/method_return_type.py, pyanalyze/name_check_visitor.py, pyanalyze/test_arg_spec.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_value.py, pyanalyze/type_object.py, pyanalyze/value.py
- Add new `can_assign()` API for typevar handling
- Add new TypeObject for storing bases and doing fancy things with them
- Cut a few places over to use `can_assign()`
- Remove AwaitableIncompleteValue
=> More typevar work

pyanalyze/name_check_visitor.py
A few things I found while profiling, and some old Python 2 branches.
=> minor optimizations

pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/name_check_visitor.py, pyanalyze/stacked_scopes.py, pyanalyze/test_arg_spec.py, pyanalyze/test_stacked_scopes.py, pyanalyze/test_value.py, pyanalyze/value.py
And use them for assignability checks.
=> Add support for properly retrieving generic bases

pyanalyze/implementation.py, pyanalyze/test_value.py, pyanalyze/value.py
- Use str() instead of repr() in assert_is_value to make errors more readable
- Use f-strings in a few Value.__str__ implementations and add some tests
=> small improvements to error messages

README.md, pyanalyze/name_check_visitor.py, pyanalyze/test_value.py, pyanalyze/value.py
=> remove is_value_compatible

pyanalyze/arg_spec.py, pyanalyze/name_check_visitor.py, pyanalyze/test_arg_spec.py, pyanalyze/test_name_check_visitor.py
Similar to the fix for Iterable in #67
=> fix Awaitable check too

pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/test_implementation.py
This method should eventually be removed.
=> remove some usage of .is_type()

pyanalyze/arg_spec.py, pyanalyze/test_arg_spec.py
Forgot to fix this before merging #74
=> fix for str.find

pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/stacked_scopes.py, pyanalyze/test_implementation.py, pyanalyze/test_stacked_scopes.py
I'm not sure this will be useful in practice very often, but #79 found
a use case in pyanalyze itself, and maybe the framework can be useful elsewhere.
=> add support for predicate constraints

pyanalyze/name_check_visitor.py
Part of #79 but should cause less disruption than the full change
=> pass args/kwargs into Signature.check_call

pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py, pyanalyze/safe.py, pyanalyze/test_implementation.py, pyanalyze/test_name_check_visitor.py, pyanalyze/value.py, pyanalyze/yield_checker.py
This helps remove some false positives from #79.
=> Make NO_RETURN_VALUE an empty union

pyanalyze/arg_spec.py, pyanalyze/test_arg_spec.py
=> Infer signature for NewType constructors

pyanalyze/name_check_visitor.py
These were guarding pre-3.6 code.
=> remove some hasattr/getattr calls

pyanalyze/test_signature.py
A function like this would be useful for landing #85, so make sure it works.
=> add a test case

pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/asynq_checker.py, pyanalyze/find_unused.py, pyanalyze/implementation.py, pyanalyze/method_return_type.py, pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py, pyanalyze/signature.py, pyanalyze/stacked_scopes.py, pyanalyze/test_self.py, pyanalyze/value.py, pyanalyze/yield_checker.py
Using pyanalyze's own `use_fstrings` check.
=> use f-strings

pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/safe.py, pyanalyze/stacked_scopes.py, pyanalyze/test_stacked_scopes.py, pyanalyze/value.py
=> Support constraints on subscript expressions

setup.py
The upcoming 1.0 release will break compatibility
=> Pin typeshed-client to below 1.0

pyanalyze/analysis_lib.py, pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/attributes.py, pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/test_config.py, pyanalyze/test_typeshed.py, pyanalyze/typeshed.py
Add the non-operative parts of #103 to avoid future merge conflicts
=> Prepare for typeshed attribute types

pyanalyze/node_visitor.py, pyanalyze/typeshed.py, pyanalyze/yield_checker.py
- Add new check from #85
- Fix a bug I noticed
=> minor fixes from typeshed

pyanalyze/annotations.py, pyanalyze/test_annotations.py, pyanalyze/value.py
=> Produce errors for more invalid type annotation

pyanalyze/config.py, pyanalyze/importer.py, pyanalyze/name_check_visitor.py, setup.py
Instead, use importlib directly
=> Stop using the nose importer

pyanalyze/importer.py
Avoid namespace package imports if possible
=> Improve the importer

pyanalyze/annotations.py, pyanalyze/extensions.py, pyanalyze/signature.py, pyanalyze/stacked_scopes.py, pyanalyze/test_annotations.py, pyanalyze/value.py
Through pyanalyze.extensions for now since it's not in typing_extensions yet.
=> Implement TypeGuards

pyanalyze/signature.py, pyanalyze/test_signature.py, pyanalyze/test_value.py
=> add can_assign() to Signature

pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/stacked_scopes.py
First step for #98 (but not closing it yet because we need to remove the old way).
=> New implementation function format

pyanalyze/annotations.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/test_annotations.py, pyanalyze/value.py
=> implement CallableValue

pyanalyze/arg_spec.py, pyanalyze/implementation.py, pyanalyze/signature.py, pyanalyze/typeshed.py, pyanalyze/yield_checker.py
=> clean up old-style implementation functions

pyanalyze/arg_spec.py, pyanalyze/config.py
More flexible replacement for a few existing config options.
=> Add new get_constructor() hook

pyanalyze/test_annotations.py
=> test Callable a bit more

pyanalyze/name_check_visitor.py, pyanalyze/test_annotations.py
=> support type[str] in 3.9

pyanalyze/arg_spec.py, pyanalyze/test_typeshed.py
=> fix TypeVar ordering

pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py, pyanalyze/test_name_check_visitor.py
Found by #85, merging it separately to reduce the size of that PR
=> Fix some Union attribute access

.gitignore, pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py, pyanalyze/signature.py, pyanalyze/test_node_visitor.py, pyanalyze/test_signature.py, pyanalyze/test_value.py, pyanalyze/value.py
=> improve error messages for incompatible values

pyanalyze/annotations.py, pyanalyze/test_annotations.py
=> fix empty tuple type

pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/name_check_visitor.py, pyanalyze/test_typeshed.py, pyanalyze/test_value.py, pyanalyze/value.py
Preparation for some other changes from the protocols branch
=> make get_generic_bases return a TypeVarMap

pyanalyze/arg_spec.py
A cache isn't much good if you don't put anything in it
=> Fix generic_bases cache

pyanalyze/test_name_check_visitor.py, pyanalyze/value.py
This time I learned my lesson and tried against the internal codebase first.
=> fix list unpacking a different way

pyanalyze/name_check_visitor.py, pyanalyze/test_implementation.py, pyanalyze/test_name_check_visitor.py
Unify dictcomp handling with other comprehensions so that we treat them the same.
=> fix dictcomp handling

pyanalyze/annotations.py, pyanalyze/test_annotations.py, pyanalyze/test_typeshed.py, pyanalyze/typeshed.py
pyanalyze didn't reject the invalid annotation in the new test case
=> don't allow TypedValue in type_from_value

pyanalyze/name_check_visitor.py
=> remove imp usage

pyanalyze/arg_spec.py, pyanalyze/test_arg_spec.py
=> handle custom __new__ a little

pyanalyze/name_check_visitor.py
=> don't show traceback if import error is suppressed

README.md, pyanalyze/__init__.py, pyanalyze/annotations.py, pyanalyze/extensions.py, pyanalyze/test_annotations.py, pyanalyze/value.py
A new mechanism for customizing checks.
=> add CustomCheck support

pyanalyze/extensions.py, pyanalyze/test_annotations.py
- Support nested usage
- Fix example
=> ExternalType improvements

pyanalyze/stacked_scopes.py, pyanalyze/test_annotations.py, pyanalyze/test_stacked_scopes.py, pyanalyze/value.py
Fixes #204 
- Preserve annotations through Constraints
- AnnotatedValue never contains a MultiValuedValue
- Add Annotated handling to boolean_value()
=> Improve Annotated handling

pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/test_implementation.py, pyanalyze/test_name_check_visitor.py, pyanalyze/value.py, pyanalyze/yield_checker.py
=> add impl for list and tuple __getitem__

pyanalyze/format_strings.py, pyanalyze/name_check_visitor.py, pyanalyze/test_format_strings.py
* Get rid of deprecated is_type calls
* Handle Unions
* Simplify and extend tests
* Add a few additional checks
=> Improve format string code

README.md, pyanalyze/__init__.py, pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/attributes.py, pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/stacked_scopes.py, pyanalyze/test_annotations.py, pyanalyze/test_arg_spec.py, pyanalyze/test_attributes.py, pyanalyze/test_config.py, pyanalyze/test_format_strings.py, pyanalyze/test_implementation.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_signature.py, pyanalyze/test_stacked_scopes.py, pyanalyze/test_typeshed.py, pyanalyze/test_value.py, pyanalyze/typeshed.py, pyanalyze/value.py
=> remove usage of UNRESOLVED_VALUE

pyanalyze/signature.py
So far this helps only in the case where both is_ellipsis_args and allow_call are True, which should be very hard to achieve. The next PRs will move towards full type checking for *args and **kwargs.
=> first step towards checking args/kwargs

pyanalyze/annotations.py, pyanalyze/error_code.py, pyanalyze/name_check_visitor.py, pyanalyze/stacked_scopes.py, pyanalyze/test_annotations.py, pyanalyze/test_name_check_visitor.py, pyanalyze/yield_checker.py
=> Improve missing return detection

README.md
Very interesting project! I am reading through its source code right now 👍
=> Fixes typo in the docs

README.md, setup.py
=> prepare release 0.4.0

docs/changelog.md, pyanalyze/annotations.py, pyanalyze/attributes.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/test_annotations.py, pyanalyze/value.py
Found by running pyanalyze on black
=> Fix two annotation bugs

.github/workflows/doc.yml
Seems unlikely to matter and I don't want to wait for it
=> don't build docs on windows

pyanalyze/__init__.py, pyanalyze/ast_annotator.py, pyanalyze/checker.py, pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py, pyanalyze/test_arg_spec.py, pyanalyze/test_attributes.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_value.py, pyanalyze/value.py
A place to store global state across modules.
=> add Checker

pyanalyze/name_check_visitor.py, pyanalyze/type_object.py, pyanalyze/value.py
In preparation for enabling TypedValue to hold structural and synthetic types.
=> Improve abstraction on TypedValue

setup.py
https://github.com/JelleZijlstra/typeshed_client/issues/30
=> Disallow typeshed-client 2

docs/changelog.md, pyanalyze/__init__.py, pyanalyze/checker.py, pyanalyze/name_check_visitor.py, pyanalyze/test_type_object.py, pyanalyze/type_object.py, pyanalyze/typeshed.py, pyanalyze/value.py
Only synthetic, non-generic protocols.
=> Basic Protocol support

pyanalyze/type_object.py
stringify_object() returns str unchanged
=> simplify TypeObject.__str__

pyanalyze/importer.py, pyanalyze/node_visitor.py, pyanalyze/typeshed.py
=> Minor typing fixes

docs/changelog.md, pyanalyze/name_check_visitor.py
I underestimated how disruptive this would be.
Removed the changelog as there is very little user-visible change in the end.
=> make IGNORE_NONE_ATTRIBUTES more lenient again

docs/changelog.md, pyanalyze/boolability.py, pyanalyze/config.py, pyanalyze/format_strings.py, pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/test_boolability.py, pyanalyze/test_format_strings.py, pyanalyze/test_implementation.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_stacked_scopes.py, pyanalyze/test_value.py, pyanalyze/type_object.py, pyanalyze/value.py
=> support ** unpacking in dict literals

docs/changelog.md, pyanalyze/config.py, pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py, pyanalyze/safe.py, pyanalyze/signature.py, pyanalyze/test_config.py, pyanalyze/test_signature.py, pyanalyze/tests.py, pyanalyze/value.py
=> Internal support for overloads

pyanalyze/__init__.py, pyanalyze/arg_spec.py, pyanalyze/asynq_checker.py, pyanalyze/extensions.py, pyanalyze/name_check_visitor.py, pyanalyze/test_extensions.py, pyanalyze/test_signature.py
=> support runtime @overload

pyanalyze/test_value.py
So these tests more closely reflect real type checking.
=> make test context more powerful

docs/changelog.md, pyanalyze/annotations.py, pyanalyze/name_check_visitor.py, pyanalyze/safe.py, pyanalyze/signature.py, pyanalyze/test_annotations.py, pyanalyze/test_attributes.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_signature.py, requirements.txt, setup.py, tox.ini
- Drop unnecessary dependencies
- Add another resource on overloads
- Remove some unused imports
=> various cleanup

docs/changelog.md, pyanalyze/error_code.py, pyanalyze/name_check_visitor.py, pyanalyze/test_annotations.py, pyanalyze/test_name_check_visitor.py
=> with and async with

docs/changelog.md, pyanalyze/suggested_type.py
=> suggested type improvements

docs/changelog.md, pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/signature.py, pyanalyze/test_annotations.py, pyanalyze/test_signature.py, pyanalyze/test_type_object.py, pyanalyze/test_value.py, pyanalyze/value.py
On the way to supporting type eval function type compatibility.
=> Minor ParamSpec improvements

docs/changelog.md, pyanalyze/name_check_visitor.py, pyanalyze/test_async_await.py
=> handle NoReturn in async def

pyanalyze/analysis_lib.py, pyanalyze/attributes.py, pyanalyze/checker.py, pyanalyze/name_check_visitor.py, pyanalyze/node_visitor.py
This will make future refactoring easier
=> make Checker compatible with CanAssignContext

docs/changelog.md, pyanalyze/name_check_visitor.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_stacked_scopes.py
Also ended up improving type inference for and/or in general.
Fixes #438
=> Fix treatment of walrus in and/or and IfExp

docs/changelog.md, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/type_object.py
=> protocol cache

docs/changelog.md, pyanalyze/annotations.py, pyanalyze/arg_spec.py, pyanalyze/attributes.py, pyanalyze/checker.py, pyanalyze/implementation.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/stubs/_pyanalyze_tests-stubs/initnew.pyi, pyanalyze/test_arg_spec.py, pyanalyze/test_attributes.py, pyanalyze/test_signature.py, pyanalyze/test_typeshed.py, pyanalyze/type_object.py, pyanalyze/typeshed.py, pyanalyze/value.py
=> pick up __init__ and __new__ from typeshed

docs/changelog.md, pyanalyze/signature.py, pyanalyze/test_typeshed.py, pyanalyze/typeshed.py
=> pick up open() signature from typeshed

pyanalyze/name_check_visitor.py, pyanalyze/test_name_check_visitor.py
=> fix conditionally declared module-scope variables

docs/changelog.md, pyanalyze/annotations.py, pyanalyze/error_code.py, pyanalyze/functions.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/test_generators.py, pyanalyze/value.py
- Support for typechecking generators
- fix self check
=> Support for typechecking generators

pyanalyze/stacked_scopes.py, pyanalyze/test_functions.py, pyanalyze/test_operations.py, pyanalyze/test_typevar.py, pyanalyze/test_value.py, pyanalyze/value.py
- add test_lots_of_constraints
- test for OrBound
- remove dead code
- test for failing __eq__
- more async generator tests
- remove unused method
=> Improve test coverage

.github/workflows/test.yml, docs/changelog.md, pyanalyze/functions.py, pyanalyze/name_check_visitor.py, pyanalyze/test_attributes.py, pyanalyze/test_extensions.py, pyanalyze/typeshed.py, tox.ini
- fix a test in 3.11
- more 3.11 workarounds
- fix last failures
- CI
- changelog
=> Support Python 3.11

setup.py
=> Remove Cython logic from setup.py

pyanalyze/analysis_lib.py
Transitional measure for internal callers that pass str
=> Allow str in files_with_extension_from_directory

docs/changelog.md, pyanalyze/arg_spec.py, pyanalyze/test_arg_spec.py
We have this internally but it keeps coming up in new places, might as well support it in pyanalyze directly.
=> Add pytest.raises support

pyanalyze/test_attributes.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_signature.py, pyanalyze/test_typeshed.py
=> Drop use of qcore.testing.Anything

docs/changelog.md, pyanalyze/name_check_visitor.py, pyanalyze/test_attributes.py
=> Fix name mangling

pyanalyze/annotations.py
Fixes python/typing_extensions#287
=> Can't use collections.abc.Callable yet

docs/changelog.md, pyanalyze/arg_spec.py, pyanalyze/functions.py, pyanalyze/name_check_visitor.py, pyanalyze/signature.py, pyanalyze/test_functions.py, pyanalyze/test_typevar.py
And better support for user-defined generic classes that I realized we were missing.
=> More PEP 695 support

docs/changelog.md, pyanalyze/checker.py
Fixes python/typing_extensions#325
=> Fix Protocol issue

docs/changelog.md, pyanalyze/test_type_object.py, pyanalyze/type_object.py
=> Apply implicit int/float promotion to subclasses

docs/changelog.md, pyanalyze/annotations.py, pyanalyze/implementation.py, pyanalyze/patma.py, pyanalyze/safe.py, pyanalyze/test_stacked_scopes.py
=> Fix isinstance on non-types

docs/changelog.md, pyanalyze/name_check_visitor.py, pyanalyze/test_name_check_visitor.py, pyanalyze/test_stacked_scopes.py
=> Fix incorrect undefined_name in doubly nested classes

docs/changelog.md, pyanalyze/error_code.py, pyanalyze/name_check_visitor.py, pyanalyze/patma.py, pyanalyze/signature.py, pyanalyze/test_operations.py, pyanalyze/test_unsafe_comparison.py, pyanalyze/test_value.py, pyanalyze/type_object.py, pyanalyze/typeshed.py, pyanalyze/value.py
This isn't ready and has some false positives even on pyanalyze's own code but I want to try it out.
=> Unsafe comparison overlap

pyanalyze/typeshed.py
Reverts quora/pyanalyze#789
Caused some problems internally due to inaccessible paths
=> Revert "Improve performance of constructing typeshed_client"

pyanalyze/asynq_checker.py
This is somewhat hacky, but otherwise most test files need to be excluded.
=> Add a flag to force impure async checks
